### PR TITLE
[CLOUDTRUST-773] Refactor POM hierarchy

### PR DESCRIPTION
**Pull request by fperot74**
Requires cloudtrust/cloudtrust-parent#1

### CODE REVIEW

**Review by AlistairDoswald — CHANGES_REQUESTED** [review]
There are a couple of problems:
1) assembly is broken. The resulting tar.gz should contain the install script, module.xml and the jar with the same structure as in the original directory structure. This is to ensure that the install can be used both from the directory and from the decompressed archive.
2) The installation is broken, instead of setting the theme, it sets an empty module block:
```
<providers>
        <provider>classpath:${jboss.home.dir}/providers/*</provider>
        <provider>module:io.cloudtrust.keycloak-OTP-push-authentication</provider>
        <provider>module:io.cloudtrust.keycloak-export</provider>
      </providers>
      <master-realm-name>master</master-realm-name>
      <scheduled-task-interval>900</scheduled-task-interval>
      <theme>
        <staticMaxAge>2592000</staticMaxAge>
        <cacheThemes>true</cacheThemes>
        <cacheTemplates>true</cacheTemplates>
        <dir>${jboss.home.dir}/themes</dir>
        <modules>
          <module>io.cloudtrust.keycloak-OTP-push-authentication</module>
          <module/>
        </modules>
      </theme>
```
Both these features worked before the PR
There might also be some rebasing work due to pr #15

**Review by AlistairDoswald — CHANGES_REQUESTED** [review]
There's still a couple of problems:
- The install.sh is now installing to `modules/system/layers/keycloak-export/main/`, but it should be installing to `modules/system/layers/keycloak-export/io/cloudtrust/keycloak-export/main/`
- the execution flag is missing from the install.sh

**Review by AlistairDoswald — CHANGES_REQUESTED** [review]
Installation, uninstall, import, export all work.

However, services.js is not in sync with the latest version of multi-token-prototype code. Update this and I can merge.
Diff is:
```
658c656
<     credentials.updateCredential = $resource(authUrl + '/admin/realms/:realm/users/:userId/credentials/:credentialId', {
---
>     credentials.updateCredentialLabel = $resource(authUrl + '/admin/realms/:realm/users/:userId/credentials/:credentialId/label', {
664c662,668
<             method : 'PUT'
---
>             method : 'PUT',
>             headers: {
>                 'Content-Type': 'text/plain;charset=utf-8'
>             },
>             transformRequest: function(credential, getHeaders) {
>                 return credential.userLabel;
>             }
```

**Comment by fperot74** [comment]
> However, services.js is not in sync with the latest version of multi-token-prototype code. Update this and I can merge.

Done

**Review by AlistairDoswald — APPROVED** [review]

**Pull request merged**
