### PR TITLE
[CLOUDTRUST-1746] Migrate to Keycloak 7.0.0 multi-token

### PR DESCRIPTION
**Pull request by fperot74**

### CODE REVIEW

**Review by lagess — COMMENTED** [review]
If I've understood well, the import is only enabled in the KC interface if the admin theme is set to ctexport, right?

**Comment by lagess** [comment]
I've tried 2 things:
- full export through the API --> OK
- import with custom required actions using the admin console --> FAIL
--> is the" fix of the import with custom required actions" part of this PR?

**Comment by lagess** [comment]
One issue discovered: setting the ctexport admin theme breaks the multi-token screen:
- set the ctexport admin theme in the master realm
- logout / login in the master realm
- open a user, select the credential tab --> i18n fails

**Comment by fperot74** [comment]
> One issue discovered: setting the ctexport admin theme breaks the multi-token screen:
> 
> * set the ctexport admin theme in the master realm
> * logout / login in the master realm
> * open a user, select the credential tab --> i18n fails

I've updated the service.js which was still a patch of 6.0.1 rather than a patch of 7.0.0

**Review by AlistairDoswald — APPROVED** [review]

**Pull request merged**
